### ISSUE TITLE
Diebold-Nixdorf Agilis

### ISSUE THREAD

**Issue by jsyfib** [cisagov/log4j-affected-db#103]
Please provide the following information.  

- Diebold-Nixdorf
- Agilis
- Version(s) affected: 3.7 / Agilis 91x SP5 / Agilis NDx SP 7 
- Status:  Affected
- Update Available:  No (patch expected 12/17/21
- Notes: No impact if HF21013 has not been applied.  If HF21013 has been applied, update to HF19024 to close the immediate threat. 
- References: https://www.dieboldnixdorf.com/en-us/apache  - See PDF in link
- Last Updated:  12/15/21

**Comment by iainDe** [comment]
This product has been added to the repository. Thank you.
