### ISSUE TITLE
Shibboleth Project Status Submission

### ISSUE THREAD

**Issue by scantor** [cisagov/log4j-affected-db#104]
# Submission Template

Please provide the following information.  

- Vendor Name: Shibboleth
- Product Name: All Products
- Version(s) affected: Identity Provider >= 3.0, All other software versions
- Status:  Not Affected
- Update Available:  No
- Notes: Third parties that package our software in various forms may introduce this library and thus create a vulnerability, and deployers are generally responsible for their own servlet container environment, and could introduce the problem themselves.
- References: https://shibboleth.net/pipermail/announce/2021-December/000253.html
- Last Updated: 2021-12-15

**Comment by iainDe** [comment]
This product has been added to the repository. Thank you.
