### ISSUE TITLE
Zendesk

### ISSUE THREAD

**Issue by ahmedmusaad** [cisagov/log4j-affected-db#108]
# Submission Template

Please provide the following information.  

- Vendor Name: Zendesk
- Product Name: All Products
- Version(s) affected: All Versions
- Status: Affected.
- Update Available: No
- Notes: Zendesk products are all cloud-based; thus there are no updates for the customers to install as the company is working on patching their infrastructure and systems.
- References: https://support.zendesk.com/hc/en-us/articles/4413583476122
- Last Updated:  2021-12-13

**Comment by iainDe** [comment]
This product has been added to the repository. Thank you.
