### ISSUE TITLE
Mulesoft Runtime, Mule Agent, Cloudhub, Anypoint Studio

### ISSUE THREAD

**Issue by datag00n** [cisagov/log4j-affected-db#111]
# Submission Template

Please provide the following information.  

- Vendor Name: Mulesoft
- Product Name: Mule Runtime, Mule Agent, Cloudhub, Anypoint Studio
- Version(s) affected: 3.x/4.x runtime/agent, 6.x/7.x studio
- Status:  Affected
- Update Available:  Yes
- References https://help.mulesoft.com/s/article/Apache-Log4j2-vulnerability-December-2021
- Last Updated:  2021-12-12

**Comment by iainDe** [comment]
This product has been added to the repository. Thank you.
