### ISSUE TITLE
Include date added to list

### ISSUE THREAD

**Issue by ghost** [cisagov/log4j-affected-db#13]
Including a column or some indication of when something was added to the list would be helpful for those of us that are maintaining larger lists sourced from multiple sources. As it stands, folks more or less need to run a dif to see whats changed (i.e. been added). Moving this to a gist so we could see revisions would be nice too. Or make the history visible under the wiki.

**Comment by justmurphy** [comment]
Thank you for your suggestion and we will take it into consideration.
