### ISSUE TITLE
Ellucian

### ISSUE THREAD

**Issue by Drehmini** [cisagov/log4j-affected-db#147]
# Submission Template #

Please provide the following information.

- Vendor Name 
    - Ellucian
- Product Name
    - Banner, Colleague, and others
- Version(s) affected
- Status: Please choose from one of the following 
    - Multiple products affected and unaffected
- Update Available: 
   -  Yes
- Notes
- References
    - Vendor response page: https://www.ellucian.com/news/ellucian-response-apache-log4j-issue
- Last Updated:
    - 12/15/2021

**Comment by iainDe** [comment]
This product has been added to the repository. Thank you.
