### ISSUE TITLE
Papercut

### ISSUE THREAD

**Issue by CatsAndUnicorns** [cisagov/log4j-affected-db#151]
Vendor Name
PaperCut
Product Name
PaperCut NG and PaperCut MF
Version(s) affected:
21.0 and later
Status:
Affected
Update Available:
Yes
Notes:
Versions 21.0 and later are impacted. Versions 20 and earlier are NOT impacted by this.
Workaround manual steps available in reference.
Upgrade to PaperCut NG/MF version 21.2.3 Now Available to resolve.
References:
Vendor response page: https://www.papercut.com/support/known-issues/?id=PO-684#ng
Last Updated:
12/16/2021

**Comment by justindmurphy** [comment]
Issue addressed by PR #243

**Comment by justmurphy** [comment]
@Darkfox7133 thank you for the submission.
