### ISSUE TITLE
Advanced Systems Concepts (formally Jscape) - ActiveMFT - Not affected

### ISSUE THREAD

**Issue by Git-Me-Some-Hub** [cisagov/log4j-affected-db#160]
# Submission Template #

Please provide the following information.

- Vendor Name: Advanced Systems Concepts (formally Jscape)
- Product Name: ActiveMFT: MFT Server, MFT Gateway, MFT Monitor
- Version(s) affected
- Status: Not Affected
- Update Available: No
- Notes: behind pay wall
- References: https://support.advsyscon.com/hc/en-us/articles/4413631831569
- Last Updated: 12/14/21

![image](https://user-images.githubusercontent.com/17930434/146435646-4b3d8ca3-30ef-4aa5-a082-04a4e23ec6b7.png)

**Comment by iainDe** [comment]
This product has been added to the repository. Thank you.
