### ISSUE TITLE
Apache Kafka not impacted

### ISSUE THREAD

**Issue by cory-at-confluent** [cisagov/log4j-affected-db#17]
# Submission Template

Please provide the following information.  

- Vendor Name: Apache
- Product Name: Kafka
- Version(s) affected: All
- Status:  Not Affected
- Update Available: No
- Notes: The current DB lists Apache Kafka as impacted. Apache Kafka uses Log4jv1, not v2.
- References: https://kafka.apache.org/cve-list
- Last Updated:  Dec 14, 2021

**Comment by ChrisSCISA** [comment]
Thank you for reaching out to CISA and we have updated our list.

**Comment by cory-at-confluent** [comment]
Thanks - unfortunately, it looks like a row was added but the previously entered row for Apache Kafka being impacted still remains.
