### ISSUE TITLE
Salesforce DataLoader <=53.0.0 vulnerable

### ISSUE THREAD

**Issue by glen-testing** [cisagov/log4j-affected-db#180]
# Submission Template #

Please provide the following information.

- Vendor Name Salesforce
- Product Name DataLoader
- Version(s) affected <=53.0.0
- Status: Fixed
- Update Available: Yes : https://github.com/forcedotcom/dataloader/releases/tag/v53.0.1
- Notes This update includes log4j 2.16.
- References https://github.com/forcedotcom/dataloader/releases/tag/v53.0.1
- Last Updated: 12/14/2021

**Comment by justmurphy** [comment]
@glen-testing thank you for submission
