### ISSUE TITLE
Update Siemens | SIMATIC WinCC V7.4

### ISSUE THREAD

**Issue by nobodyman1** [cisagov/log4j-affected-db#183]
- Vendor Name: Siemens
- Product Name: WinCC 7.4
- Version(s) affected: All versions < V7.4 SP1
- Status: Not Affected
- Update Available: No
- Notes: listed as affected in V1.0-V1.1 of the advisory
- References: [https://cert-portal.siemens.com/productcert/pdf/ssa-661247.pdf]()
- Last Updated: 12/17/2021

**Comment by Lcerkov** [comment]
@nobodyman1 The Siemens entries (including SIMATIC Wincc) have been updated according to the latest advisory. Thank you.
