### ISSUE TITLE
Nutanix - Security Advisory #0023

### ISSUE THREAD

**Issue by nosecguy** [cisagov/log4j-affected-db#185]
Vendor | Product | Version | Status | Update Available | Notes | References | Last Updated
-- | -- | -- | -- | -- | -- | -- | --
Nutanix | Multiple | Multiple | Affected | Yes | - | [Security Advisory #0023](https://download.nutanix.com/alerts/Security_Advisory_0023.pdf)| 12/16/2021

**Comment by justmurphy** [comment]
Thank you for the submission.
