### ISSUE TITLE
ISC DHCP not affected

### ISSUE THREAD

**Issue by vrisk** [cisagov/log4j-affected-db#195]
# Submission Template #

Please provide the following information.

- Vendor Name:  Internet Systems Consortium
- Product Name: ISC DHCP, aka dhcpd
- Version(s) affected: all
- Status: Please choose from one of the following: Not Affected
- Update Available: Yes or No (If Yes, please provide link to information)
- Notes: no JAVA code
- References: https://www.isc.org/blogs/2021-log4j/
- Last Updated: December 17, 2021

**Comment by iainDe** [comment]
This product has been added to the repository. Thank you.
