### ISSUE TITLE
PA File Sight from Power Admin NOT affected

### ISSUE THREAD

**Issue by poweradminllc** [cisagov/log4j-affected-db#198]
# Submission Template #

Please provide the following information.

- Vendor Name: Power Admin LLC
- Product Name: PA File Sight
- Version(s) affected: NONE
- Status: Not Affected
- Update Available: No
- Notes
- References: https://www.poweradmin.com/blog/solarwinds-hack-our-safety-measures/
- Last Updated: 17 December 2021

**Comment by iainDe** [comment]
This product has been added to the repository. Thank you.
