### ISSUE TITLE
[RE-POSTING]Akamai SIEM Splunk Connector fix available. 

### ISSUE THREAD

**Issue by jrobins04** [cisagov/log4j-affected-db#203]
# Submission Template #

Please provide the following information.

Vendor Name: Akamai
Product Name: SIEM Splunk Connector
Version(s) affected: All
Status: Fixed
Update Available: Yes - https://splunkbase.splunk.com/app/4310/
Notes: v1.4.11 is the new recommendation for mitigation of log4j vulnerabilities.
References: https://splunkbase.splunk.com/app/4310/
Last Updated: 15 December 2021

**Comment by jrobins04** [comment]
This was posted 2 days back https://github.com/cisagov/log4j-affected-db/issues/97 and @iainDe had made the changes to the repo. But, from today it's been reverted back to previous state. Kindly do the updates.

**Comment by iainDe** [comment]
Reverted back. Thank you
