### ISSUE TITLE
An update to ExtraHop Networks

### ISSUE THREAD

**Issue by jcostlow** [cisagov/log4j-affected-db#206]
Vendor Name : ExtraHop
Product Name : Reveal(x)
Version(s) affected : >8.4.7, >8.5.4, >8.6.5, >=8.7 
Status: Fixed
Update Available: Yes
Notes : All versions above are fixed.
References : https://forums.extrahop.com/t/extrahop-update-on-log4shell/8148
Last Updated: 12/17

Dear Maintainer:
I believe the previous entry made on Dec 14 is clear about versions that need to be updated. This makes it clear which versions to not need to be updated. Please add this as another row below the first row.
Thank
Jeff Costlow
Deputy CISO
ExtraHop Networks, Inc.

**Comment by Lcerkov** [comment]
@jcostlow Hello, this doesn't follow our current methodology as it would create duplicative entries for thousands of products. To add clarification to your current entry, we suggest the addition of a note that explains that versions above those listed as affected are considered fixed. Would this satisfy that requirement? Thank you.

**Comment by jcostlow** [comment]
Then you may just add a note that says

"Versions  >8.4.7, >8.5.4, >8.6.5 and >=8.7  are fixed"

Does that work?
Thank you for keeping the list.

**Comment by Lcerkov** [comment]
@jcostlow Thank you -- this note has been added!
