### ISSUE TITLE
Ruckus

### ISSUE THREAD

**Issue by FrankE-Aqura** [cisagov/log4j-affected-db#22]
# Submission Template

- Ruckus
- Virtual SmartZone (vSZ)
- 5.1 to 6.0
- Status:  Affected
- Update Available:  No
- Notes: Also affects SmartZone, Unleashed Multi-Site Manager (UMM) and FlexMaster products
- https://support.ruckuswireless.com/security_bulletins/313
- https://support.ruckuswireless.com/security_bulletins_downloads/313?type=pdf
- https://support.ruckuswireless.com/security_bulletins_downloads/313?type=txt
- Last Updated:  2021 12 13

**Comment by ChrisSCISA** [comment]
Thank you for providing this information and we will update the list.
