### ISSUE TITLE
Add PTC items into list

### ISSUE THREAD

**Issue by KwadwoBCISA** [cisagov/log4j-affected-db#225]
Please add the following submissions into the repository:
Company - PTC (https://www.ptc.com/en/documents/log4j)
Products:
Axeda (https://www.ptc.com/en/support/article/CS358990)
Thingworx platform (https://www.ptc.com/en/support/article/CS358901)
Questra IDM (under investigation - contact me before adding)

**Comment by iainDe** [comment]
Working on getting all affected products on the list
