### ISSUE TITLE
Recommend splitting the readme up by major vendor

### ISSUE THREAD

**Issue by droidmonkey** [cisagov/log4j-affected-db#234]
The current readme is not sustainable and PR merges have already come to a point where multiple parties are trying to edit the same parts of the monofile. Recommend splitting the guts of the readme by major vendor, perhaps with an "other" that captures the rest. This would keep formatting nightmares to a minimum and allow vendors to submit prs easily for their own products without fear of messing up everyone else. 

Good work so far though!

**Comment by Firminator** [comment]
+1

**Comment by Lcerkov** [comment]
@droidmonkey Thank you for your suggestion. We have changed the way we maintain data on the backend (in alphabetized YAML data files) and the Software List is now autogenerated. This may solve some of the issues you mentioned (formatting nightmares). You can see instructions for contributing [here ](https://github.com/cisagov/log4j-affected-db/blob/develop/CONTRIBUTING.md)and an example PR [here](https://github.com/cisagov/log4j-affected-db/blob/develop/PULL-EXAMPLE.md).

**Comment by droidmonkey** [comment]
Excellent thanks!
