### ISSUE TITLE
Azure DevOps Server

### ISSUE THREAD

**Issue by Ramanean** [cisagov/log4j-affected-db#27]
# Submission Template

Please provide the following information.  

- Vendor Name : Microsoft
- Product Name : Azure DevOps Server
- Version(s) affected : Azure DevOps Server 2020 & earlier, TFS 2017 and later
- Status:  Affected 
- Update Available:  No 
- Notes - Patch is yet to be available 
- References :https://devblogs.microsoft.com/devops/azure-devops-and-azure-devops-server-and-the-log4j-vulnerability/ 
- Last Updated:  12/14/2021

**Comment by jessehouwing** [comment]
Fixed by #71

**Comment by justmurphy** [comment]
Thank you for the submission.  Updated.
