### ISSUE TITLE
Azure DevOps

### ISSUE THREAD

**Issue by Ramanean** [cisagov/log4j-affected-db#28]
- Vendor Name : Microsoft
- Product Name : Azure DevOps (Cloud)
- Version(s) affected - Cloud Version
- Status:  Fixed 
- Update Available:  No
- Notes :  Cloud version has been patched already
- References : https://devblogs.microsoft.com/devops/azure-devops-and-azure-devops-server-and-the-log4j-vulnerability/ (Patched)
- Last Updated:  12/14/2021

**Comment by jessehouwing** [comment]
Fixed by #71

**Comment by justmurphy** [comment]
Thank you for your submission.  Updated.
