### ISSUE TITLE
ExtraHop Reveal(x)

### ISSUE THREAD

**Issue by jcostlow** [cisagov/log4j-affected-db#30]
- Vendor Name : ExtraHop
- Product Name : Reveal(x)
- Version(s) affected : <=8.4.6, <=8.5.3, <=8.6.4
- Status:  Affected
- Update Available:  Yes
- Notes : Contains vulnerable code but not likely to get unauthenticated user input to the log4j component
- References : https://forums.extrahop.com/t/extrahop-update-on-log4shell/8148
- Last Updated:  12/14

**Comment by Lcerkov** [comment]
Thank you! This issue has been added.
