### ISSUE TITLE
Siemens | Capital

### ISSUE THREAD

**Issue by Ramanean** [cisagov/log4j-affected-db#31]
Please provide the following information.  

- Vendor Name : Siemens 
- Product Name : Capital 
- Version(s) affected : All versions >= 2019.1 SP1912 only if Teamcenter integration feature is used
- Status:  Affected
- Update Available: Yes
- Notes : Mitigation - https://support.sw.siemens.com/en-US/knowledge-base/MG618363
- References : https://cert-portal.siemens.com/productcert/pdf/ssa-661247.pdf
- Last Updated:  12/15/2021

**Comment by justmurphy** [comment]
Added, thank you (working on the rest).
