### ISSUE TITLE
Siemens | Comos Desktop App

### ISSUE THREAD

**Issue by Ramanean** [cisagov/log4j-affected-db#32]
Please provide the following information.  

- Vendor Name : Siemens 
- Product Name : Comos Desktop App
- Version(s) affected : All versions 
- Status: Affected
- Update Available: Yes
- Notes : None 
- References : https://cert-portal.siemens.com/productcert/pdf/ssa-661247.pdf
- Last Updated:  12/15/2021

**Comment by justmurphy** [comment]
Added, thank you (working on the rest)
