### ISSUE TITLE
Siemens | Desigo CC Advanced Reporting

### ISSUE THREAD

**Issue by Ramanean** [cisagov/log4j-affected-db#33]
Please provide the following information.  

- Vendor Name : Siemens 
- Product Name : Desigo CC Advanced Reporting:
- Version(s) affected : V4.0, V4.1, V4.2, V5.0, V5.1
- Status:  Affected
- Update Available: Yes
- Notes : None
- References : https://cert-portal.siemens.com/productcert/pdf/ssa-661247.pdf
- Last Updated:  12/15/2021

**Comment by justmurphy** [comment]
Added, thank you (working on the rest)
