### ISSUE TITLE
Siemens  | Desigo CC Info Center

### ISSUE THREAD

**Issue by Ramanean** [cisagov/log4j-affected-db#34]
- Vendor Name : Siemens 
- Product Name : Desigo CC Info Center
- Version(s) affected : V5.0, V5.1
- Status:  Affected
- Update Available: Yes
- Notes : None
- References : https://cert-portal.siemens.com/productcert/pdf/ssa-661247.pdf
- Last Updated:  12/15/2021

**Comment by justmurphy** [comment]
Thank you for submitting the issue.  Product updated.
