### ISSUE TITLE
Adding Squash TM as a product affected by log4j

### ISSUE THREAD

**Issue by jpjoly-git** [cisagov/log4j-affected-db#340]
# Submission Template #

Please provide the following information.

- Vendor Name: HENIX
- Product Name: Squash TM
- Version(s) affected: 1.21.7 - 1.22.9 - 2.0.3 - 2.1.5 - 2.2.0 - 3.0.2
- Status: Fixed
- Update Available: Yes. Fixed versions are downloadable here : https://tm-en.doc.squashtest.com/v3/downloads.html#download-previous-versions
- Last Updated: 12/22/2021

**Comment by jpjoly-git** [comment]
Here is the line to be added in the file SOFTWARE-LIST.md line 1041 by the time: 
| Henix | Squash | 1.21.7 - 1.22.9 - 2.0.3 - 2.1.5 - 2.2.0 - 3.0.1 | Fixed | Yes | [Henix](https://tm-en.doc.squashtest.com/v3/downloads.html) | | | 21/22/2021 |

**Comment by jpjoly-git** [comment]
Sorry, the closure was the consequence of a misclick...

**Comment by justmurphy** [comment]
@jpjoly-git thank you for the submission
