### ISSUE TITLE
Siemens | E-Car OC Cloud Application

### ISSUE THREAD

**Issue by Ramanean** [cisagov/log4j-affected-db#35]
Please provide the following information.  

- Vendor Name : Siemens 
- Product Name : E-Car OC Cloud Application
- Version(s) affected : All versions < 2021-12-13
- Status:  Affected
- Update Available: Yes
- Notes : None
- References : https://cert-portal.siemens.com/productcert/pdf/ssa-661247.pdf
- Last Updated:  12/15/2021

**Comment by justmurphy** [comment]
Thank you for submitting the issue.  Updated.
