### ISSUE TITLE
Siemens | EnergyIP Prepay

### ISSUE THREAD

**Issue by Ramanean** [cisagov/log4j-affected-db#36]
Please provide the following information.  

- Vendor Name : Siemens 
- Product Name : EnergyIP Prepay
- Version(s) affected : V3.7, V3.8
- Status:  Affected
- Update Available: Yes
- Notes : None
- References : https://cert-portal.siemens.com/productcert/pdf/ssa-661247.pdf
- Last Updated:  12/15/2021

**Comment by justmurphy** [comment]
Thank you for submitting the issue.  Updated.
