### ISSUE TITLE
Siemens | Industrial Edge Manangement Hub

### ISSUE THREAD

**Issue by Ramanean** [cisagov/log4j-affected-db#41]
Please provide the following information.  

- Vendor Name : Siemens 
- Product Name : Industrial Edge Manangement Hub
- Version(s) affected : All versions
- Status:  Affected
- Update Available: Yes
- Notes : None
- References : https://cert-portal.siemens.com/productcert/pdf/ssa-661247.pdf
- Last Updated:  12/15/2021

**Comment by justmurphy** [comment]
Thank you for submitting the issue.  Updated.
