### ISSUE TITLE
[Product Submission]: HPE/Micro Focus - Data Protector 9.09

### ISSUE THREAD

**Issue by oneofthedamons** [cisagov/log4j-affected-db#421]
### Product vendor

HPE/Micro Focus

### Product name

Data Protector

### Product version(s)

9.09

### Product status

Fixed

### Product update

Available

### Product update link

https://portal.microfocus.com/s/article/KM000003243

### Last updated

2021-12-17

### Notes

Data Protector 9.09 was published by HPE but is supported by Micro Focus now

### References

https://portal.microfocus.com/s/article/KM000003050

**Comment by justmurphy** [comment]
Thank you for your submission @oneofthedamons
