### ISSUE TITLE
[Product Submission]: Micro Focus - Data Protector versions 10.2-11

### ISSUE THREAD

**Issue by oneofthedamons** [cisagov/log4j-affected-db#422]
### Product vendor

Micro Focus

### Product name

Data Protector

### Product version(s)

10.20, 10.30, 10.40, 10.50, 10.60, 10.70, 10.80, 10.90, 10.91, 11.00

### Product status

Fixed

### Product update

Available

### Product update link

https://portal.microfocus.com/s/article/KM000003052

### Last updated

2021-12-13

### References

https://portal.microfocus.com/s/article/KM000003050

**Comment by justmurphy** [comment]
Thank you for your submission @oneofthedamons
