### ISSUE TITLE
Siemens | Mendix Applications

### ISSUE THREAD

**Issue by Ramanean** [cisagov/log4j-affected-db#43]
Please provide the following information.  

- Vendor Name : Siemens 
- Product Name : Mendix Applications
- Version(s) affected : All versions
- Status:  Not Affected
- Update Available: Yes
- Notes : Recommended to upgrade log4j if used within the project
- References : https://cert-portal.siemens.com/productcert/pdf/ssa-661247.pdf
- Last Updated:  12/15/2021

**Comment by justmurphy** [comment]
Thank you for submitting the issue.  Updated.
