### ISSUE TITLE
Siemens | Mindsphere Cloud Application

### ISSUE THREAD

**Issue by Ramanean** [cisagov/log4j-affected-db#44]
Please provide the following information.  

- Vendor Name : Siemens 
- Product Name : Mindsphere Cloud Application
- Version(s) affected : All versions < 2021-12-11
- Status:  Affected
- Update Available: Yes
- Notes : Fixed on Cloud version
- References : https://cert-portal.siemens.com/productcert/pdf/ssa-661247.pdf
- Last Updated:  12/15/2021

**Comment by justmurphy** [comment]
Thank you for submitting the issue.  Updated.
