### ISSUE TITLE
Siemens | Operation Scheduler

### ISSUE THREAD

**Issue by Ramanean** [cisagov/log4j-affected-db#47]
Please provide the following information.  

- Vendor Name : Siemens 
- Product Name : Operation Scheduler
- Version(s) affected : All versions >= V1.1.3
- Status:  Affected
- Update Available: Yes
- Notes : Block incoming and outgoing connections
- References : https://cert-portal.siemens.com/productcert/pdf/ssa-661247.pdf
- Last Updated:  12/15/2021

**Comment by justmurphy** [comment]
Thank you for submitting the issue.  Updated.
