### ISSUE TITLE
Siemens | SIGUARD DSA

### ISSUE THREAD

**Issue by Ramanean** [cisagov/log4j-affected-db#48]
Please provide the following information.  

- Vendor Name : Siemens 
- Product Name : SIGUARD DSA
- Version(s) affected : V4.2, V4.3, V4.4
- Status:  Affected
- Update Available: Yes
- Notes : None
- References : https://cert-portal.siemens.com/productcert/pdf/ssa-661247.pdf
- Last Updated:  12/15/2021

**Comment by justmurphy** [comment]
Thank you for submitting the issue.  Updated.
