### ISSUE TITLE
Rapid7's Product Information

### ISSUE THREAD

**Issue by ic3scrap3r** [cisagov/log4j-affected-db#5]
- Rapid7
- https://www.rapid7.com/blog/post/2021/12/14/update-on-log4shells-impact-on-rapid7-solutions-and-systems/?mkt_tok=NDExLU5BSy05NzAAAAGBVaccW1DOLSfEsfTNwEJksv_1nK1muJSFze-Lle90mKtAO78nSdjwPdzqXskNIi9qZCAGQODD42mYRK4YPlQkjhn38E27HQxFHdHAkypEOsh8

- Product Names and Version info available at link above.
- Status:  Affected
- Update Available:  Yes or No (If Yes, please provide link to information)
- References](https://www.rapid7.com/blog/post/2021/12/14/update-on-log4shells-impact-on-rapid7-solutions-and-systems/?mkt_tok=NDExLU5BSy05NzAAAAGBVaccW1DOLSfEsfTNwEJksv_1nK1muJSFze-Lle90mKtAO78nSdjwPdzqXskNIi9qZCAGQODD42mYRK4YPlQkjhn38E27HQxFHdHAkypEOsh8)
- Last Updated:  12/14/21

**Comment by Lcerkov** [comment]
Thank you! This issue has been added.
