### ISSUE TITLE
Siemens | SIMATIC WinCC V7.4

### ISSUE THREAD

**Issue by Ramanean** [cisagov/log4j-affected-db#50]
Please provide the following information.  

- Vendor Name : Siemens 
- Product Name : SIGUARD DSA
- Version(s) affected : All versions < V7.4 SP1
- Status:  Affected
- Update Available: Yes
- Notes : None
- References : https://cert-portal.siemens.com/productcert/pdf/ssa-661247.pdf
- Last Updated:  12/15/2021

**Comment by justmurphy** [comment]
Thank you for submitting the issue.  Updated.
