### ISSUE TITLE
Siemens | Siveillance Command

### ISSUE THREAD

**Issue by Ramanean** [cisagov/log4j-affected-db#53]
Please provide the following information.  

- Vendor Name : Siemens 
- Product Name : Siveillance Command
- Version(s) affected : All versions >= 4.16.2.1
- Status:  Affected
- Update Available: Yes
- Notes : None
- References : https://cert-portal.siemens.com/productcert/pdf/ssa-661247.pdf
- Last Updated:  12/15/2021

**Comment by justmurphy** [comment]
Thank you for submitting the issue.  Updated.
