### ISSUE TITLE
Siemens | Siveillance Identity V1.5

### ISSUE THREAD

**Issue by Ramanean** [cisagov/log4j-affected-db#55]
Please provide the following information.  

- Vendor Name : Siemens 
- Product Name : Siveillance Identity V1.5
- Version(s) affected : All versions
- Status:  Affected
- Update Available: Yes
- Notes : None
- References : https://cert-portal.siemens.com/productcert/pdf/ssa-661247.pdf
- Last Updated:  12/15/2021

**Comment by justmurphy** [comment]
Thank you for submitting the issue.  Updated.
