### ISSUE TITLE
Siemens | Solid Edge Wiring Harness Design

### ISSUE THREAD

**Issue by Ramanean** [cisagov/log4j-affected-db#58]
Please provide the following information.  

- Vendor Name : Siemens 
- Product Name : Solid Edge Wiring Harness Design
- Version(s) affected : All versions >= 2020 SP2002 only if Teamcenter integration feature is used
- Status:  Affected
- Update Available: Yes
- Notes : None
- References : https://cert-portal.siemens.com/productcert/pdf/ssa-661247.pdf
- Last Updated:  12/15/2021

**Comment by justmurphy** [comment]
Thank you for submitting the issue.  Updated.
