### ISSUE TITLE
Siemens | Spectrum Power 4

### ISSUE THREAD

**Issue by Ramanean** [cisagov/log4j-affected-db#59]
Please provide the following information.  

- Vendor Name : Siemens 
- Product Name : Spectrum Power 4
- Version(s) affected : All versions only with component jROS in version 3.0.0
- Status:  Affected
- Update Available: Yes
- Notes : None
- References : https://cert-portal.siemens.com/productcert/pdf/ssa-661247.pdf
- Last Updated:  12/15/2021

**Comment by justmurphy** [comment]
Thank you for submitting the issue.  Updated.
