### ISSUE TITLE
Dutch NCSC list of (non) vulnerable software

### ISSUE THREAD

**Issue by MetzieNL** [cisagov/log4j-affected-db#6]
Dear CISA, the Dutch NCSC has already started a community driven list on sunday and as of this moment it contains over 1600 lines of information. Instead of starting (yet) another list maybe you can link to that list instead and ask members to contribute there.

Link: https://github.com/NCSC-NL/log4shell

Kind regards,
Danny Metz

**Comment by adulau** [comment]
I strongly support @MetzieNL comment.  Did CISA evaluate the option to work on the NSCS-NL repo directly or at least do pull-request? That would be easier for everyone.

**Comment by milankowww** [comment]
+1 from me. I know it's not a competition but with your current 7 forks and 67 stars, compared to 264 forks and 679 stars at the NL repository, you have much to gain by contributing where everybody else does. You can keep this as a redirection project, and I'm sure NCSC-NL would appreciate helping hand.

**Comment by certrik** [comment]
+1 I fully agree with the comments so far. Let's not duplicate information.

**Comment by milankowww** [comment]
@justmurphy no comment, just "closed"? Polite. Santa crosses you from his list this Christmas.
