### ISSUE TITLE
Siemens | Spectrum Power 7

### ISSUE THREAD

**Issue by Ramanean** [cisagov/log4j-affected-db#60]
Please provide the following information.  

- Vendor Name : Siemens 
- Product Name : Spectrum Power 7
- Version(s) affected : All versions < V2.30 SP2 only with component jROS
- Status:  Affected
- Update Available: Yes
- Notes : None
- References : https://cert-portal.siemens.com/productcert/pdf/ssa-661247.pdf
- Last Updated:  12/15/2021

**Comment by justmurphy** [comment]
Thank you for submitting the issue.  Updated.
