### ISSUE TITLE
Siemens | VeSys

### ISSUE THREAD

**Issue by Ramanean** [cisagov/log4j-affected-db#62]
Please provide the following information.  

- Vendor Name : Siemens 
- Product Name : VeSys
- Version(s) affected : All versions >= 2019.1 SP1912 only if Teamcenter integration feature is used
- Status:  Affected
- Update Available: Yes
- Notes : None
- References : https://cert-portal.siemens.com/productcert/pdf/ssa-661247.pdf
- Last Updated:  12/15/2021

**Comment by justmurphy** [comment]
Thank you for submitting the issue.  Updated.
