### ISSUE TITLE
Siemens | Xpedition EDM Client

### ISSUE THREAD

**Issue by Ramanean** [cisagov/log4j-affected-db#63]
Please provide the following information.  

- Vendor Name : Siemens 
- Product Name :  Xpedition EDM Client
- Version(s) affected : VX.2.6 - VX.2.10
- Status:  Affected
- Update Available: Yes
- Notes : None
- References : https://cert-portal.siemens.com/productcert/pdf/ssa-661247.pdf
- Last Updated:  12/15/2021

**Comment by justmurphy** [comment]
Thank you for your submission.  Updated.
