### ISSUE TITLE
IBM Power HMC

### ISSUE THREAD

**Issue by ghost** [cisagov/log4j-affected-db#82]
Please provide the following information.  

- Vendor Name: IBM
- Product Name: Power HMC
- Version(s) affected: V9.2.950.0 & V10.1.1010.0
- Status:  Affected
- Update Available:  Yes 
- Notes: None
- References: https://www.ibm.com/support/pages/node/6526172?myns=pwrsmc&mynp=OCSGGSNP&mync=E&cm_sp=pwrsmc-_-OCSGGSNP-_-E
- Last Updated:  12/15/21

**Comment by iainDe** [comment]
This product has been added to the repository. Thank you.
