### ISSUE TITLE
APC / Schneider Electric Powerchute Network Shutdown

### ISSUE THREAD

**Issue by AHelsby** [cisagov/log4j-affected-db#85]
# Submission Template

Please provide the following information.  

- Vendor Name APC / Schneider Electric
- Product Name Powerchute Network Shutdown
- Version(s) affected 4.4.1, 4.4,4.3,4.2
- Status:  Fixed
- Update Available:  No
- Notes Mitigation instructions to remove the affected class
- References https://community.exchange.se.com/t5/APC-UPS-Data-Center-Backup/Log4-versions-used-in-Powerchute-vulnerable/m-p/379866/highlight/true#M47345
- Last Updated:  2021/12/15

**Comment by justindmurphy** [comment]
Issue addressed by PR #242

**Comment by justmurphy** [comment]
@AHelsby thank you for the submission.
