### ISSUE TITLE
APC / Schneider Electric Powerchute Business Edition.

### ISSUE THREAD

**Issue by AHelsby** [cisagov/log4j-affected-db#86]
- Vendor Name APC / Schneider Electric
- Product Name Powerchute Business Edition
- Version(s) affected v9.5, v10.0, v10.0.1, v10.0.2, v10.0.3, v10.0.4
- Status:  Fixed
- Update Available:  No
- Notes Mitigation instructions to remove the affected class
- References https://community.exchange.se.com/t5/APC-UPS-Data-Center-Backup/Log4-versions-used-in-Powerchute-vulnerable/m-p/379866/highlight/true#M47345
- Last Updated:  2021/12/15

**Comment by justindmurphy** [comment]
Issue addressed by PR #242

**Comment by justmurphy** [comment]
@AHelsby thank you for the submission
