### ISSUE TITLE
AWS Pointer is outdated and multiple products are now fixed

### ISSUE THREAD

**Issue by jeffsec-aws** [cisagov/log4j-affected-db#9]
# Submission Template

Please provide the following information.  

- Vendor Name : AWS
- Product Name: as per your table
- Version(s) affected: as per your table
- Status:  Fixed
- Update Available:  Yes
- Notes
- References: https://aws.amazon.com/security/security-bulletins/AWS-2021-006/ [the link used in the table is outdated and is not updated inline like the one provided here)
- Last Updated:  Date of last update

**Comment by justmurphy** [comment]
@jeffsec-aws could you please advise if your suggestions have been reflected in the table?
