### ISSUE TITLE
Akamai SIEM Splunk Connector fix available.

### ISSUE THREAD

**Issue by jrobins04** [cisagov/log4j-affected-db#97]
# Submission Template

Please provide the following information.  

- **Vendor Name**: Akamai
- **Product Name**: SIEM Splunk Connector
- **Version(s) affected**: All
- **Status**:  Fixed
- **Update Available**:  Yes - https://splunkbase.splunk.com/app/4310/
- **Notes**: v1.4.11 is the new recommendation for mitigation of log4j vulnerabilities.
- **References**: https://splunkbase.splunk.com/app/4310/
- **Last Updated**:  15 December 2021

**Comment by iainDe** [comment]
This product has been added to the repository. Thank you.
